# -*- coding: utf-8 -*-
"""Test_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c7k13FKWBzaTUcfTdpilDi2mublPM8BO
"""

import unittest
import pickle
from analysis.nneigh import nearest_neighbor

class TestNear(unittest.TestCase):
  def test_NN(self):
      """
      Test that the nearest address is chosen
      """
      OSfile = open('C:/Users/Rae-Djamaal/Anaconda3/Lib/Git_Uploads'\
                   '/analysis/TX_OOS', 'rb')
      ISfile = open('C:/Users/Rae-Djamaal/Anaconda3/Lib/Git_Uploads'\
                   '/analysis/TX_tail', 'rb')   
      T_OS = pickle.load(OSfile) 
      T_IS = pickle.load(ISfile)
      result = nearest_neighbor(T_OS, T_IS, return_dist=True)
      Addresses = list(result.iloc[[0,2,3,4,9],2])
      self.assertEqual(Addresses, ['603 Showers Rd,Palmview,TX',\
                                   '947 Versailles Dr,El Paso,TX',\
                                   '471 FM 416,Streetman,TX',\
                                   '4136 Chandler Hwy,Tyler,TX',\
                                   '4554 FM,Gary,TX'])


if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)